---

- name: Backup Trove sources.list file
  command: cp /etc/apt/sources.list /etc/apt/sources.list.trove
  
- name: Restore orginial sources.list file
  command: cp /etc/apt/sources.list.bk /etc/apt/sources.list
   
- name: Update the repo list in apt
  command: apt-get update